version: "3.7"

services:
  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports: 
      - "6379:6379"
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
      - "9001:8081"
